/* automatically generated by ./auth_modules.sh basic digest ntlm negotiate
 * do not edit
 */
#include "squid.h"

extern AUTHSSETUP authSchemeSetup_basic;
extern AUTHSSETUP authSchemeSetup_digest;
extern AUTHSSETUP authSchemeSetup_ntlm;
extern AUTHSSETUP authSchemeSetup_negotiate;
void authSchemeSetup(void)
{
	authSchemeAdd("basic", authSchemeSetup_basic);
	authSchemeAdd("digest", authSchemeSetup_digest);
	authSchemeAdd("ntlm", authSchemeSetup_ntlm);
	authSchemeAdd("negotiate", authSchemeSetup_negotiate);
}
