/* automatically generated by ./store_modules.sh ufs aufs coss diskd null
 * do not edit
 */
#include "squid.h"

extern STSETUP storeFsSetup_ufs;
extern STSETUP storeFsSetup_aufs;
extern STSETUP storeFsSetup_coss;
extern STSETUP storeFsSetup_diskd;
extern STSETUP storeFsSetup_null;
void storeFsSetup(void)
{
	storeFsAdd("ufs", storeFsSetup_ufs);
	storeFsAdd("aufs", storeFsSetup_aufs);
	storeFsAdd("coss", storeFsSetup_coss);
	storeFsAdd("diskd", storeFsSetup_diskd);
	storeFsAdd("null", storeFsSetup_null);
}
